import aplicacao_campo_jpg_json from "./aplicacao_campo.jpg.asset.json";
import cevada_brotos_jpg_json from "./cevada_brotos.jpg.asset.json";
import cevada_mao_jpg_json from "./cevada_mao.jpg.asset.json";
import foto_agroleite_castro_2025_jpg_json from "./foto_agroleite_castro_2025.jpg.asset.json";
import foto_assinatura_palacio_iguacu_jpg_json from "./foto_assinatura_palacio_iguacu.jpg.asset.json";
import foto_inauguracao_biopark_2026_jpg_json from "./foto_inauguracao_biopark_2026.jpg.asset.json";
import foto_palacio_iguacu_2023_jpg_json from "./foto_palacio_iguacu_2023.jpg.asset.json";
import icone_molecula_verde_jpg_json from "./icone_molecula_verde.jpg.asset.json";
import logo_ferticerto_png_json from "./logo_ferticerto.png.asset.json";
import logo_sanfer_jpg_json from "./logo_sanfer.jpg.asset.json";
import manga_caixa_jpg_json from "./manga_caixa.jpg.asset.json";
import manga_esteira_jpg_json from "./manga_esteira.jpg.asset.json";
import morango_bandeja_jpg_json from "./morango_bandeja.jpg.asset.json";
import placas_penicillium_jpg_json from "./placas_penicillium.jpg.asset.json";
import placas_penicillium_placas_jpg_json from "./placas_penicillium_placas.jpg.asset.json";
import produto_embalagem_25L_png_json from "./produto_embalagem_25L.png.asset.json";
import mapa_brasil_pr_jpg_json from "./mapa_brasil_pr.jpg.asset.json";

export const aplicacao_campo_jpg = aplicacao_campo_jpg_json.url;
export const cevada_brotos_jpg = cevada_brotos_jpg_json.url;
export const cevada_mao_jpg = cevada_mao_jpg_json.url;
export const foto_agroleite_castro_2025_jpg = foto_agroleite_castro_2025_jpg_json.url;
export const foto_assinatura_palacio_iguacu_jpg = foto_assinatura_palacio_iguacu_jpg_json.url;
export const foto_inauguracao_biopark_2026_jpg = foto_inauguracao_biopark_2026_jpg_json.url;
export const foto_palacio_iguacu_2023_jpg = foto_palacio_iguacu_2023_jpg_json.url;
export const icone_molecula_verde_jpg = icone_molecula_verde_jpg_json.url;
export const logo_ferticerto_png = logo_ferticerto_png_json.url;
export const logo_sanfer_jpg = logo_sanfer_jpg_json.url;
export const manga_caixa_jpg = manga_caixa_jpg_json.url;
export const manga_esteira_jpg = manga_esteira_jpg_json.url;
export const morango_bandeja_jpg = morango_bandeja_jpg_json.url;
export const placas_penicillium_jpg = placas_penicillium_jpg_json.url;
export const placas_penicillium_placas_jpg = placas_penicillium_placas_jpg_json.url;
export const produto_embalagem_25L_png = produto_embalagem_25L_png_json.url;
export const mapa_brasil_pr_jpg = mapa_brasil_pr_jpg_json.url;
